version: "3"
services:
  backend:
    image: deltologic/frontend:1.0.0
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    image: deltologic/backend:1.0.0
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
